name: MS Teams Notification

on: [push, pull_request]

jobs:
  success:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # this is the new step using the ms-teams-notification action
      - name: Notify dedicated teams channel
        uses: skitionek/notify-microsoft-teams@master
        if: ${{success()}}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "title": "Build succeeded"
            }
