name: MS Teams Notification

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # this is the new step using the ms-teams-notification action
      - name: Notify dedicated teams channel
        uses: thechetantalwar/teams-notify@v2
        with:
          teams_webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          message: "Hello World"
