name: Check notification

on: workflow_dispatch

jobs:
  with_raw:
    name: One with raw data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook: ${{ secrets.TEAMS_WEBHOOK }}
          title: "Test notification"
          text: "This is a test notification"
          color: "00FF00"
          raw: true
  without_raw:  
    name: One without raw data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook: ${{ secrets.TEAMS_WEBHOOK }}
          title: "Test notification"
          text: "This is a test notification"
          color: "00FF00"
          
