name: MS Teams Notification

on: [push, pull_request]

jobs:
  success:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # this is the new step using the ms-teams-notification action
      - name: Notify dedicated teams channel
        run: |
          curl -H 'Content-Type: application/json' -d '{"text": "Hello World"}' ${{ secrets.MSTEAMS_WEBHOOK }}
