name: MS Teams Notification

on: [push, pull_request]

jobs:
  success:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # this is the new step using the ms-teams-notification action
      - name: Notify dedicated teams channel
        run: |
          echo '{"type": "AdaptiveCard","body": [{"type": "TextBlock","text": "Hello World!"}]}' > card.json
          curl -H 'Content-Type: application/json' -d @card.json ${{ secrets.MSTEAMS_WEBHOOK }}
